#!/bin/bash
# Copyright 2020 Ryan Barry
# See LICENSE file for licensing details.

if [ -z "$VIRTUAL_ENV" -a -d venv/ ]; then
    . venv/bin/activate
fi

if [ -z "$PYTHONPATH" ]; then
    export PYTHONPATH="lib:src"
else
    export PYTHONPATH="lib:src:$PYTHONPATH"
fi

flake8
black --diff --check src tests

coverage run --source=src,lib -m pytest -rP -v "$@"
coverage report -m
