{
 "title": "Grafana Operator Overview",
 "description": "Metrics about Grafana",
 "tags": [
  "grafana",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheusds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Active instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "up{juju_charm=\"grafana-k8s\"}"
    }
   ]
  },
  {
   "title": "Dashboard count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "grafana_stat_totals_dashboard" }
   ]
  },
  {
   "title": "User count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "grafana_stat_total_users" }
   ]
  },
  {
   "title": "Playlist count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "grafana_stat_total_playlists" }
   ]
  },
  {
   "title": "Grafana version",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "topk(1, grafana_info or grafana_build_info)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "http status codes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (statuscode) (irate(grafana_http_request_duration_seconds_bucket{juju_charm=\"grafana-k8s\"}[5m]))",
     "legendFormat": "{{statuscode}}",
     "target": "dev.grafana.cb-office.alerting.active_alerts"
    }
   ]
  },
  {
   "title": "Requests by routing group",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(grafana_api_response_status_total[5m]))",
     "legendFormat": "api"
    },
    {
     "expr": "sum(irate(grafana_proxy_response_status_total[5m]))",
     "legendFormat": "proxy"
    },
    {
     "expr": "sum(irate(grafana_page_response_status_total[5m]))",
     "legendFormat": "web"
    }
   ]
  },
  {
   "title": "Most used handlers",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 5 },
   "targets": [
    {
     "expr": "sort(topk(8, sum by (handler) (grafana_http_request_duration_seconds_bucket{juju_charm=\"grafana-k8s\"})))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Grafana performance",
   "type": "timeseries",
   "description": "Aggregated over all Grafana nodes.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_goroutines{juju_charm=\"grafana-k8s\"})",
     "legendFormat": "go routines",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "sum(process_resident_memory_bytes{juju_charm=\"grafana-k8s\"})",
     "legendFormat": "memory usage"
    },
    {
     "expr": "rate(process_cpu_seconds_total{juju_charm=\"grafana-k8s\"}[$__rate_interval]) * 100",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "HTTP Request Durations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grafana_http_request_duration_seconds_bucket{juju_charm=\"grafana-k8s\"}[$__interval])) by (le,handler))",
     "legendFormat": "{{ handler }}"
    }
   ]
  }
 ]
}