name: Build/Test

on:
  workflow_call:
    secrets:
      CHARMHUB_TOKEN:
        required: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: tox -e unit

  integration-test:
    name: Integration tests (microk8s)
    runs-on: ubuntu-22.04
    needs:
      - lint
      - unit-test
    steps:
      - name: Set up docker qemu
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Checkout local
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          path: charm
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checkout test pebble Juju
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          repository: juju/juju
          path: juju
          ref: 7f388dc0ba5eaebae797fe2494ad49aea6ceecc8
      - name: run killsnoop
        uses: JarvusInnovations/background-action@v1
        with:
          run: |
            sudo apt-get update && sudo apt-get -y install bpfcc-tools python3-psutil && ls && sudo python3 ${GITHUB_WORKSPACE}/charm/src/killsnoop.py &
          wait-on: |
            file:///tmp/compiled
          tail: true
          log-output-resume: stderr
          wait-for: 10m
          log-output: stderr,stdout # same as true
          log-output-if: true
          working-directory: /tmp
      - name: Get prefsrc
        run: |
          echo "IPADDR=$(ip -4 -j route get 2.2.2.2 | jq -r '.[] | .prefsrc')" >> $GITHUB_ENV
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.26-strict/stable
          juju-channel: 3.1/edge
          microk8s-group: snap_microk8s
          microk8s-addons: "hostpath-storage dns metallb:${{ env.IPADDR }}-${{ env.IPADDR }}"
      - name: Run integration tests
        run: |
          cd ${GITHUB_WORKSPACE}/charm && tox -e integration
      - name: View audit log
        if: always()
        run: |
          cat ${GITHUB_WORKSPACE}/audit.log
