name: Pull Requests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - goss-integration-tests  # TODO - remove once merged to main

jobs:
  pull-request:
    name: PR
    runs-on: ubuntu-latest
    steps:
      - name: Install Goss
        run: |
          curl -L https://github.com/goss-org/goss/releases/download/v0.4.8/goss-linux-amd64 -o /usr/local/bin/goss
          chmod +x /usr/local/bin/goss

      - name: Inherited PR Workflow
        uses: canonical/observability/.github/workflows/charm-pull-request.yaml@main
        # TODO: The below option was removed because syntax does not allow it and should be inherited. Verify this!
        # secrets: inherit
        with:
          ip-range: 10.64.140.43/30
