name: Release Charm to Edge and Publish Libraries

on:
  push:
    branches:
      - main
      - track/1

jobs:
  release:
    uses: canonical/observability/.github/workflows/charm-release.yaml@feature/v1
    secrets: inherit
